name: yemek_tarifi_uygulamasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "icons/iosIcon.png"
  image_path_android: "icons/androidIcon.png"

flutter:
  uses-material-design: true

  assets:
    - images/yemek.webp
